version: '3'

silent: true

includes:
  omt: 
    taskfile: taskfile.omt.yaml
    flatten: true
  tools: taskfile.tools.yaml
  go: languages/go.yaml
  rust: languages/rust.yaml

tasks:
  default:
    - task --list --sort none