version: '3'

silent: true

includes:
  # tools: taskfile.tools.yaml
  # apps: taskfile.apps.yaml
  # lang: taskfile.languages.yaml
  # git: taskfile.git.yaml
  # sudo: taskfiles/sudo.yaml
  # wsl: taskfiles/wsl.yaml
  # awesome:
  #   taskfile: taskfile.awesome.yaml
  #   flatten: true
  # maintenance:
  #   taskfile: taskfile.maintenance.yaml
  #   flatten: true
  lib: lib.yaml
  omt: 
    taskfile: omt.yaml
    flatten: true
  modules: 
    taskfile: modules.yaml
    flatten: true

tasks:
  default:
    - task: help
    - task: check-updates
  
  help:
    - |
      echo "Usage: omt <command>:<actions> -- [options]"
      echo ""
      echo "Commands:"
      echo -e "  tools \t Commands for managing tools"
      echo -e "  apps \t\t Commands for managing apps"
      echo ""
      echo "See 'omt <command>:help' for more information (eg. omt tools:help or omt apps:help)."