version: '3'

silent: true

includes:
  omt: 
    taskfile: taskfile.omt.yaml
    flatten: true
  tools: taskfile.tools.yaml
  lang: taskfile.languages.yaml

tasks:
  default:
    - task --list --sort none