version: '3'

silent: true

vars:
  OS: 
    sh: echo '{{ .OS | default "linux" }}'

includes:
  omt: 
    taskfile: taskfile.omt.yaml
    flatten: true
  tools: taskfile.tools.yaml
  lang: taskfile.languages.yaml
  git: taskfile.git.yaml
  oslib: taskfile.oslib.yaml
  sudo: taskfiles/sudo.yaml

tasks:
  default:
    - task --list --sort none
    - task: check-updates
