version: '3'

silent: true

includes:
  tools: tools.yaml
  apps: apps.yaml
  lang: languages.yaml
  lib: 
    taskfile: lib.yaml
    flatten: true

tasks:
  default:
    - task --list
    - task: check-updates
