version: '3'

silent: true

includes:
  omt: 
    taskfile: taskfile.omt.yaml
    flatten: true
  tools: taskfile.tools.yaml
  lang: taskfile.languages.yaml
  git: taskfile.git.yaml
  oslib: 
    taskfile: taskfile.{{ .OS }}.yaml
    optional: true

tasks:
  default:
    - task --list --sort none